# Generated by Django 3.0.2 on 2020-01-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=105)),
                ('location', models.CharField(max_length=105)),
                ('datetime', models.DateTimeField()),
                ('activity', models.TextField()),
            ],
        ),
    ]
