# Generated by Django 3.0.2 on 2020-02-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200124_1320'),
        ('core', '0003_plan_attendees'),
    ]

    operations = [
    ]
