# Generated by Django 3.0.2 on 2020-02-08 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_merge_20200208_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attending', to=settings.AUTH_USER_MODEL),
        ),
    ]
